spring:
  application:
    name: spline-api
    version: ${VERSION:1.0-snapshot}
  jpa:
    hibernate:
        ddl-auto: create-drop
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: H2
    show-sql: true
  jackson:
    serialization-inclusion: non_null
info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}

server:
    port: 8081

mongo:
    hostQuery: 192.168.99.100:27017
    databaseQuery: axon_query

neo4j:
    host: 192.168.99.100:7474
    username: neo4j
    password: password

katharsis:
    resourcePackage: se.spline.api
    domainName: http://localhost:${server.port}
    pathPrefix: /api
